import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
 {
  _id:"5bcea364-8c95-4b9e-86d3-483d4f762278",
  name:"Royal Azure - Blue American Diamond Silver Plated Drop Earring",
  description:"With your elegant charm and the confidence you hold, you are nothing short of a royalty, lady. Portray that right with the splendid shine of Blue American Diamond Silver Plated Drop Earrings by Alankar. This classic piece of beauty is curated with gorgeous American diamonds and blue stones designed in the pattern of a dual-layered flower that finely leaves space for the teardrop to fall wonderfully at the bottom. The grace and refinement they carry surely make them a match for the minimal and voguish choices you make.",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1710996874/jwellery/royal_azure_stud.jpg",
  currentPrice:"600",
  originalPrice:"869",
  inStock:true,
  badge_type:"New",
  ratings:4.6,
  materialUsed:"Brass",
  plating:"Silver",
  genstone:"American Diamond",
  color:["Blue","Silver"],
  size:"small",
  length:"3 cm",
  width:"1 cm",
  weight:"56 gm"
 },
 {
  _id:"bbefcf8f-ff04-45f5-84d5-2de377e642c5",
  name:"Rose Gold-Plated American Diamond Studded Drop Earrings",
  description:"What a wonderful world it is, and what a wonderful choice are the American Diamond Studded Rose Gold-Plated Drop Earrings by Alankar. Curated with care and exquisite craftsmanship, these earrings bring elegance to reality with their intricate detailing and precisely cut American diamonds. The American stones are given a stunning shape, and the golden outline around them just does wonders for the overall muse.",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1710997924/jwellery/rose_gold.jpg",
  currentPrice:"699",
  originalPrice:"1199",
  inStock:true,
  badge_type:"Trending",
  ratings:4.8,
  materialUsed:"Brass",
  plating:"Rose Gold-Plated",
  genstone:"American Diamond",
  color:["white","rose gold"],
  size:"small",
  length:"3 cm",
  width:"1 cm",
  weight:"20 gm"
 },
 {
  _id:"0df37ceb-e1ee-4820-97dc-3fad6f6ccdf0",
  name:"Pink Floral Kundan Beaded Meenakari Gold-Plated Chandbali Earrings",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1710998715/jwellery/gold_plated_chandbali.jpg",
  currentPrice:"1099",
  originalPrice:"2457",
  inStock:true,
  badge_type:"New",
  ratings:4.0,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Kundan",
  color:["pink"],
  size:"medium",
  length:"5 cm",
  width:"3 cm",
  weight:"60 gm"
 },
 {
  _id:"bd762766-2b5a-47f3-8fe8-21cb1125a2db",
  name:"Green Floral Kundan Beaded Meenakari Gold-Plated Chandbali Earrings",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1710999972/jwellery/green_floral_beaded_kundan.jpg",
  currentPrice:"1849",
  originalPrice:"2865",
  inStock:true,
  badge_type:"Trending",
  ratings:4.9,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Kundan",
  color:["green","gold"],
  size:"medium",
  length:"5 cm",
  width:"3 cm",
  weight:"60 gm"
 },
 {
  _id:"f60f862b-0752-4ad9-acf2-0991c6453919",
  name:"Handpainted Gold Plated Yellow lotus Inspired Jhumka",
  description:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711000507/jwellery/gold_plated_yellow_jhumka.jpg",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"",
  currentPrice:"649",
  originalPrice:"1000",
  inStock:true,
  badge_type:"Sale",
  ratings:3.8,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Pearl",
  color:["yellow"],
  size:"medium",
  length:"4 cm",
  width:"2 cm",
  weight:"55 gm"
 },
 {
  _id:"648632b6-1731-49cf-8551-32791a9b63e1",
  name:"Pretty Leaves AD Rose Gold-Plated Drop Earrings",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711001317/jwellery/leave_rose_gold_earrings.jpg",
  currentPrice:"500",
  originalPrice:"899",
  inStock:true,
  badge_type:"New",
  ratings:3.5,
  materialUsed:"Brass",
  plating:"Rose Gold",
  genstone:"American Diamond",
  color:["rose gold"],
  size:"long",
  length:"7 cm",
  width:"1 cm",
  weight:"30 gm"
 },
 {
  _id:"291c288e-6c60-4a77-b092-4d62e0c3354c",
  name:"American Diamond Rose Gold Plated Bangle Set",
  description:"",
  brandName:"Alankar",
  category:"Bangles",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711039212/jwellery/american-diamond-rose-gold-plated-bangle.jpg",
  currentPrice:"1049",
  originalPrice:"4089",
  inStock:true,
  badge_type:"Sale",
  ratings:3.9,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"American Diamond",
  color:['rose gold'],
  size:"",
  length:"",
  width:"",
  weight:"44 gm"
 },
 {
  _id:"6566aafe-fd01-4056-b8ce-5652881a6fae",
  name:"Red Studded Floral Pearl Oxidised Silver Earrings",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711001722/jwellery/red_studded_oxidized.jpg",
  currentPrice:"259",
  originalPrice:"999",
  inStock:true,
  badge_type:"Sale",
  ratings:2.9,
  materialUsed:"German Silver",
  plating:"Silver",
  genstone:"Artificial Stones",
  color:["red","silver"],
  size:"small",
  length:"2 cm",
  width:"1.5 cm",
  weight:"10 gm"
 },
 {
  _id:"93bfb878-46e0-4a30-97aa-6fd3775cc0a7",
  name:"Embellished Kundan Hair Chain",
  description:"",
  brandName:"Alankar",
  category:"Hair Accessories",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711045533/jwellery/kundan-hair-chain.jpg",
  currentPrice:"743",
  originalPrice:"2875",
  inStock:true,
  badge_type:"New",
  ratings:4.0,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Kundan",
  color:["gold"],
  size:"",
  length:"",
  width:"",
  weight:"50 gm"
 },
 {
  _id:"71880823-2c46-4259-beb6-0090e7be36c3",
  name:"Mint Green Floral Teardrop Oxidised Silver Stud Earrings",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711002917/jwellery/mint_green_floral_earring.jpg",
  currentPrice:"567",
  originalPrice:"1250",
  inStock:true,
  badge_type:"Trending",
  ratings:4.7,
  materialUsed:"German Silver",
  plating:"Silver",
  genstone:"Artificial Stone",
  color:["mint green","silver"],
  size:"small",
  length:"4 cm",
  width:"2 cm",
  weight:"22 gm"
 },
 {
  _id:"e3582c28-09f3-499a-80e2-6bb1fd2d98b8",
  name:"Stylish Floral Gunmetal Drop Earrings",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711003405/jwellery/stylish_floral_gunmetal_earring.jpg",
  currentPrice:"1249",
  originalPrice:"3559",
  inStock:true,
  badge_type:"New",
  ratings:3.0,
  materialUsed:"Alloy",
  plating:"Silver",
  genstone:"Artificial Stone",
  color:["silver"],
  size:"medium",
  length:"8 cm",
  width:"4 cm",
  weight:"26 gm"
 },
 {
  _id:"5480f65f-3fb3-4913-8745-adbb5d996701",
  name:"Goddess Laxmi Gold Plated Real Kemp Jewellery Set",
  description:"",
  brandName:"Alankar",
  category:"Necklaces",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711041222/jwellery/gold-plated-goddess-laxmi-dual-necklace-and-earrings-set.jpg",
  currentPrice:"1903",
  originalPrice:"5055",
  inStock:true,
  badge_type:"New",
  ratings:4.6,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Pearl",
  color:["gold"],
  size:"",
  length:"",
  width:"",
  weight:"50 gm"
 },
 {
  _id:"d3ed3d70-6b79-4ea7-aa18-39d701234226",
  name:"Dual Plated Jhumkas with Mesmerizing Peacock Design",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711004068/jwellery/peacock_design_earring.jpg",
  currentPrice:"899",
  originalPrice:"2049",
  inStock:true,
  badge_type:"New",
  ratings:3.9,
  materialUsed:"Oxidised",
  plating:"Silver",
  genstone:"Artificial Stone",
  color:["silver","red"],
  size:"medium",
  length:"6 sm",
  width:"2 cm",
  weight:"14 gm"
 },
 {
  _id:"e0e96683-47a7-417d-907a-fb9d989b2fd3",
  name:"Gold-Plated Jhumka Earrings with Pearls Drop",
  description:"",
  brandName:"Alankar",
  category:"Earrings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711004440/jwellery/gold_plated_jhumka_with_pearl_drop.jpg",
  currentPrice:"499",
  originalPrice:"1175",
  inStock:true,
  badge_type:"Selling",
  ratings:3.4,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Pearl",
  color:["gold"],
  size:"small",
  length:"3 cm",
  width:"1.5 cm",
  weight:"20 gm"
 },
 {
  _id:"1dd49c22-c22b-4ada-af1a-f7ebb8407c21",
  name:"Green Kundan Gold Plated Set of 2 Bangle Set",
  description:"Happiness looks gorgeous on you, and you must wear it all the time. One way to do it is with the Green Kundan Gold Plated Set of 2 Bangle Set by Alankar. Crated in the traditional style, these bangles are gold-plated and have the classic design of kundan studded circles placed one after another to embrace your wrists with elegance. With its green outline that resembles nature, growth, and positivity, this set is sure to add grace to your look and joy to your heart",
  brandName:"Alankar",
  category:"Bangles",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711039916/jwellery/green-gold-plated-bangles.jpg",
  currentPrice:"719",
  originalPrice:"2569",
  inStock:true,
  badge_type:"Trending",
  ratings:4.8,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Kundan",
  color:["green","gold"],
  size:"",
  length:"",
  width:"",
  weight:"58 gm"
 },
 {
  _id:"2f0340ee-fd63-4dd4-b21e-f97a4b7ba676",
  name:"Set of 24 Silver Color Bangles",
  description:"",
  brandName:"Alankar",
  category:"Bangles",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711039655/jwellery/white-golden-set-of-24-bangles.jpg",
  currentPrice:"1279",
  originalPrice:"4599",
  inStock:true,
  badge_type:"Sale",
  ratings:4.2,
  materialUsed:"Brass",
  plating:"Silver",
  genstone:"None",
  color:["silver"],
  size:"",
  length:"",
  width:"",
  weight:"65 gm"
 },
 {
  _id:"8f8954a3-f39c-42f2-b2f8-ab09341dd055",
  name:"Cubic Zirconia Studded Solitaire Silver Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711026860/jwellery/cubic-zirconia-studded-solitaire-silver-ring.jpg",
  currentPrice:"999",
  originalPrice:"2099",
  inStock:true,
  badge_type:"Sale",
  ratings:4.5,
  materialUsed:"92.5 Sterling Silver",
  plating:"Silver",
  genstone:"Cubic Zirconia",
  color:["silver"],
  size:"",
  length:"",
  width:"",
  weight:"3.5 gm"
 },
 {
  _id:"1585c6c2-9e2c-495d-892a-46e26685874b",
  name:"Choti with kundans and pearls",
  description:"",
  brandName:"Alankar",
  category:"Hair Accessories",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711045893/jwellery/choti-with-kundans-and-pearls.jpg",
  currentPrice:"589",
  originalPrice:"2607",
  inStock:true,
  badge_type:"Sale",
  ratings:4.2,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Kundan",
  color:["white"],
  size:"",
  length:"",
  width:"",
  weight:"30 gm"
 },
 {
  _id:"3129c056-d786-4aa9-87c4-e7fcb828a0ec",
  name:"Gold Toned Blooming Flower Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711027252/jwellery/gold-toned-blooming-flower-ring.jpg",
  currentPrice:"499",
  originalPrice:"1756",
  inStock:true,
  badge_type:"Sale",
  ratings:3.6,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Artificial Stone",
  color:["green","gold"],
  size:"adjustable",
  length:"",
  width:"",
  weight:"8 gm"
 },
 {
  _id:"d1be038a-e35c-491f-971a-d0ddaa1bb161",
  name:"Rose Gold Blooming Flower Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711027556/jwellery/rose-gold-pearl-studded-american-diamond-statement-ring.jpg",
  currentPrice:"689",
  originalPrice:"2400",
  inStock:true,
  badge_type:"New",
  ratings:3.8,
  materialUsed:"Brass",
  plating:"Rose Gold",
  genstone:"American Diamond",
  color:["pink","rose gold"],
  size:"adjustable",
  length:"",
  width:"",
  weight:"8 gm"
 },
 {
  _id:"be3db5b1-1e0a-42aa-a0c8-1487d8e12f3a",
  name:"Oxidised Silver Plated Dancing Peacock Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711027955/jwellery/oxidised-silver-plated-wings-ring.jpg",
  currentPrice:"549",
  originalPrice:"1749",
  inStock:true,
  badge_type:"Trending",
  ratings:4.6,
  materialUsed:"German Silver",
  plating:"",
  genstone:"",
  color:["silver"],
  size:"adjustable",
  length:"",
  width:"",
  weight:"7 gm"
 },
 {
  _id:"b8f11901-adca-468d-acff-01848eb2c82e",
  name:"Gold-Plated Magenta and Green Adjustable Ring in Floral Patterned Studded with American Diamond Ruby and Emerald",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711028396/jwellery/gold-plated-magenta-and-green-adjustable-ring-in-floral-patterned.jpg",
  currentPrice:"1099",
  originalPrice:"3699",
  inStock:true,
  badge_type:"Trending",
  ratings:4.8,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"American Diamond",
  color:["green","magenta","gold"],
  size:"adjustable",
  length:"",
  width:"",
  weight:"10 gm"
 },
 {
  _id:"a0156a6f-e0a8-4fcb-bab9-17a780e4b46a",
  name:"Multilayer Beaded Silver and Gold Threaded Necklace",
  description:"",
  brandName:"Alankar",
  category:"Necklaces",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711042033/jwellery/multilayer-beaded-silver-and-gold-threaded-necklace.jpg",
  currentPrice:"679",
  originalPrice:"2745",
  inStock:true,
  badge_type:"Sale",
  ratings:3.9,
  materialUsed:"Alloy",
  plating:"Gold",
  genstone:"Artificial Stones",
  color:["gold","silver"],
  size:"",
  length:"",
  width:"",
  weight:"40 gm"
 },
 {
  _id:"0ed9abf7-fc33-461d-b1be-2350abaf9ed1",
  name:"Purple Gunmetal-Plated American Diamond Studded Adjustable Ring in Floral Pattern",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711028769/jwellery/purple-gunmetal-plated-american-diamond-studded-adjustable-ring.jpg",
  currentPrice:"489",
  originalPrice:"999",
  inStock:true,
  badge_type:"Sale",
  ratings:4.3,
  materialUsed:"Brass",
  plating:"Silver",
  genstone:"American Stone",
  color:["purple"],
  size:"adjustable",
  length:"",
  width:"",
  weight:"7 gm"
 },
 {
  _id:"c407212a-6c4f-4dd1-a8c1-1a58ad51b11d",
  name:"Gold Plated American Diamond Studded Nose Ring",
  description:"",
  brandName:"Alankar",
  category:"Nose Ring",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711043536/jwellery/gold-plated-american-diamond-studded-nose-ring.jpg",
  currentPrice:"389",
  originalPrice:"1656",
  inStock:true,
  badge_type:"Sale",
  ratings:3.6,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"American Diamond",
  color:["gold"],
  size:"",
  length:"2.5 cm",
  width:"1.5 cm",
  weight:"4 gm"
 },
 {
  _id:"5deb9ad9-0f2e-4f30-8e30-72dbd720d344",
  name:"Set of 2 Rose Gold Plated Bangles Set",
  description:"",
  brandName:"Alankar",
  category:"Bangles",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711040840/jwellery/rose-gold-plated-bangles.jpg",
  currentPrice:"479",
  originalPrice:"2499",
  inStock:true,
  badge_type:"New",
  ratings:3.6,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"None",
  color:["rose gold"],
  size:"",
  length:"",
  width:"",
  weight:"30 gm"
 },
 {
  _id:"33ed4d80-6f01-4224-b11f-ab122e45e40c",
  name:"Antique Motif Oxidised Silver Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711029068/jwellery/antique-motif-oxidised-silver-ring.jpg",
  currentPrice:"929",
  originalPrice:"1799",
  inStock:true,
  badge_type:"Sale",
  ratings:3.8,
  materialUsed:"92.5 Sterling Silver",
  plating:"Silver",
  genstone:"None",
  color:["silver"],
  size:"",
  length:"",
  width:"",
  weight:"4 gm"
 },
 {
  _id:"c722908e-2317-40b0-924a-2df632909a9b",
  name:"Heart Link American Diamond Gold-Plated Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711029513/jwellery/heart-link-american-diamond-gold-plated-ring.jpg",
  currentPrice:"609",
  originalPrice:"1200",
  inStock:true,
  badge_type:"Trending",
  ratings:4.7,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"American Diamond",
  color:["gold"],
  size:"",
  length:"",
  width:"",
  weight:"4 gm"
 },
 {
  _id:"6dfde488-fd1a-4c47-94b0-75c95b1b83e7",
  name:"Multicolor Peacock Half-Flower Beaded Gold-Plated Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711029843/jwellery/multicolor-peacock-half-flower-beaded-gold-plated-ring.jpg",
  currentPrice:"899",
  originalPrice:"2879",
  inStock:true,
  badge_type:"Sale",
  ratings:4.3,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"American Diamond",
  color:["gold", "multi"],
  size:"adjustable",
  length:"",
  width:"",
  weight:"8 gm"
 },
 {
  _id:"498d5851-753b-423c-bfee-35e2fd8faa33",
  name:"Emerald Green Silver Plated Solitaire Ring",
  description:"",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711030320/jwellery/emerald-green-silver-plated-solitaire-ring.jpg",
  currentPrice:"607",
  originalPrice:"1299",
  inStock:true,
  badge_type:"New",
  ratings:4.2,
  materialUsed:"Brass",
  plating:"Silver",
  genstone:"American Diamond",
  color:["green","silver"],
  size:"",
  length:"",
  width:"",
  weight:"4 gm"
 },
 {
  _id:"3b0f7fe1-9bd4-41d3-b56b-51dc196cff36",
  name:"Designer Gold Plated NoseRing/Nath With Pearl Chain",
  description:"",
  brandName:"Alankar",
  category:"Nose Ring",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711043267/jwellery/designer-gold-plated-nosering-nath-with-pearl-chain.jpg",
  currentPrice:"675",
  originalPrice:"2500",
  inStock:true,
  badge_type:"Trending",
  ratings:4.9,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Pearl",
  color:["gold"],
  size:"",
  length:"",
  width:"",
  weight:"5 gm"
 },
 {
  _id:"e9098ac9-1d6a-4f82-b119-8d5247b96e4e",
  name:"Ruby German Silver Oxidised Jewellery Set",
  description:"",
  brandName:"Alankar",
  category:"Necklaces",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711041522/jwellery/oxidized-ruby-studded-set-in-bird-pattern.jpg",
  currentPrice:"899",
  originalPrice:"3689",
  inStock:true,
  badge_type:"Trending",
  ratings:4.8,
  materialUsed:"German Silver",
  plating:"Silver",
  genstone:"Ruby",
  color:["silver"],
  size:"",
  length:"",
  width:"",
  weight:"60 gm"
 },
 {
  _id:"0df06df2-522a-40ae-bbcb-c1d3304cc535",
  name:"Diamond Shape Kundan Hair Band",
  description:"",
  brandName:"Alankar",
  category:"Hair Accessories",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711046544/jwellery/diamond-shape-kundan-hair-band.jpg",
  currentPrice:"456",
  originalPrice:"1785",
  inStock:true,
  badge_type:"Trending",
  ratings:4.7,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Kundan",
  color:["white","gold"],
  size:"",
  length:"",
  width:"",
  weight:"20 gm"
 },
 {
  _id:"f66af208-68fe-4cd3-a677-9d89ad08db82",
  name:"Sterling Silver Leaf Adjustable Ring",
  description:"It's beautiful to love the ordinary, the leaf. Alankar's Embossed Leaf Oxidized Silver Ring is here to picture the quote. Crafted on a silver band, this ring has a beautiful leaf embossed on it. So, don't wait! Take this moment to make your special someone feel super special.",
  brandName:"Alankar",
  category:"Rings",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711030721/jwellery/sterling-silver-leaf-adjustable-ring.jpg",
  currentPrice:"249",
  originalPrice:"799",
  inStock:true,
  badge_type:"New",
  ratings:3.9,
  materialUsed:"Silver",
  plating:"Silver",
  genstone:"None",
  color:["silver"],
  size:"adjustable",
  length:"",
  width:"",
  weight:"3 gm"
 },
 {
  _id:"3932f0fe-e0b4-411c-8cf7-644e98124c3d",
  name:"Kemp Stones Beads Gold Plated Bun Pin Hair Accessory",
  description:"",
  brandName:"Alankar",
  category:"Hair Accessories",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711046822/jwellery/kemp-stone-bun-pin.jpg",
  currentPrice:"559",
  originalPrice:"1420",
  inStock:true,
  badge_type:"Sale",
  ratings:3.9,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"Artificial Stone",
  color:["red","white","gold","green"],
  size:"",
  length:"",
  width:"",
  weight:"25 gm"
 },
 {
  _id:"974b4711-8765-4606-beca-a8a61bdf1c9e",
  name:"Purple Stones Silver Plated Bangles Set",
  description:"",
  brandName:"Alankar",
  category:"Bangles",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711040357/jwellery/purple-stone-silver-plated-bangle.jpg",
  currentPrice:"799",
  originalPrice:"3499",
  inStock:true,
  badge_type:"New",
  ratings:4.0,
  materialUsed:"Alloy",
  plating:"Silver",
  genstone:"Artificial Stone",
  color:["purple","silver"],
  size:"",
  length:"",
  width:"",
  weight:"30 gm"
 },
 {
  _id:uuid(),
  name:"Gold Plated Studded Circle Evil Eye Necklace",
  description:"",
  brandName:"Alankar",
  category:"Necklaces",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711042407/jwellery/gold-plated-stone-studded-evil-eye-necklace.jpg",
  currentPrice:"299",
  originalPrice:"1067",
  inStock:true,
  badge_type:"New",
  ratings:3.5,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"None",
  color:["gold"],
  size:"",
  length:"",
  width:"",
  weight:"50 gm"
 },
 {
  _id:"258c60dd-3329-44c1-8797-e6bc6b7492c3",
  name:"Gold Plated Leaf Shaped American Diamond Studded Nath/Nose Ring",
  description:"",
  brandName:"Alankar",
  category:"Nose Ring",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711042889/jwellery/gold-plated-leaf-shaped-american-diamond-studded-nath-nose-ring.jpg",
  currentPrice:"449",
  originalPrice:"869",
  inStock:true,
  badge_type:"New",
  ratings:3.9,
  materialUsed:"Brass",
  plating:"Gold",
  genstone:"American Diamond",
  color:["gold"],
  size:"",
  length:"2.5 cm",
  width:"1.5 cm",
  weight:"4 gm"
 },
 {
  _id:"0314e6b2-9d92-40e3-8a44-2f4ef39d27e9",
  name:"Silver-Toned Stone-Studded Anklets",
  description:"",
  brandName:"Alankar",
  category:"Anklets",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711043975/jwellery/silver-toned-stone-studded-anklets.jpg",
  currentPrice:"399",
  originalPrice:"1239",
  inStock:true,
  badge_type:"New",
  ratings:3.2,
  materialUsed:"German Silver",
  plating:"Silver",
  genstone:"Artificial Stone",
  color:["silver"],
  size:"",
  length:"26 cm",
  width:"1 cm",
  weight:"25 gm"
 },
 {
  _id:"a354f29e-0caf-4c37-b999-324d41249cbe",
  name:"Antique Chunks - Oxidised Silver Plated Broad Anklets-Set of 2",
  description:"",
  brandName:"Alankar",
  category:"Anklets",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711044383/jwellery/antique-oxidised-silver-plated-traditional-broad-anklets.jpg",
  currentPrice:"1869",
  originalPrice:"5789",
  inStock:true,
  badge_type:"Trending",
  ratings:4.8,
  materialUsed:"German Silver",
  plating:"Silver",
  genstone:"None",
  color:["silver"],
  size:"",
  length:"26 cm",
  width:"2 cm",
  weight:"50 gm"
 },
 {
  _id:"25098fae-6622-4eeb-8480-958cf44ee106",
  name:"Sterling Silver Floral Black Thread Anklet",
  description:"This gorgeous sterling anklet by Alankar can be worn with any outfit. The adjustable floral anklet consists of black thread and secured around your ankle through drawstring closure.",
  brandName:"Alankar",
  category:"Anklets",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711044838/jwellery/steling-silver-floral-black-thread-anklet-bracelet.jpg",
  currentPrice:"259",
  originalPrice:"1056",
  inStock:true,
  badge_type:"Sale",
  ratings:3.6,
  materialUsed:"Silver",
  plating:"Silver",
  genstone:"None",
  color:["silver","black"],
  size:"",
  length:"",
  width:"",
  weight:"3.8 gm"
 },
 {
  _id:"d732e38e-9049-49c2-b919-5ecd612c1199",
  name:"Beads Kundan Ghungroo Gold Plated Anklets",
  description:"",
  brandName:"Alankar",
  category:"Anklets",
  imageUrl:"https://res.cloudinary.com/bijaylaxmibehera/image/upload/v1711045242/jwellery/kundan-ghungroo-gold-plated-anklets.jpg",
  currentPrice:"859",
  originalPrice:"2203",
  inStock:true,
  badge_type:"New",
  ratings:4.3,
  materialUsed:"Alloy",
  plating:"Gold",
  genstone:"Kundan",
  color:["gold"],
  size:"",
  length:"",
  width:"",
  weight:"70 gm"
 },

//  {
//   _id:uuid(),
//   name:"",
//   description:"",
//   brandName:"",
//   category:"",
//   imageUrl:"",
//   currentPrice:"",
//   originalPrice:"",
//   inStock:"",
//   badge_type:"",
//   ratings:"",
//   materialUsed:"",
//   plating:"",
//   genstone:"",
//   color:[],
//   size:"",
//   length:"",
//   width:"",
//   weight:""
//  },

];
